
const $=id=>document.getElementById(id);
const mediaTypeInput=$('mediaType'),mediaUrlInput=$('mediaUrl'),titleInput=$('title'),baseUrlInput=$('baseUrl'),testBtn=$('testBtn'),generateBtn=$('generateBtn'),resultUrl=$('resultUrl'),openBtn=$('openBtn'),downloadQrBtn=$('downloadQrBtn'),statusBox=$('status'),qrBox=$('qrcode'),previewWrap=$('previewWrap'),imagePreview=$('imagePreview'),videoPreview=$('videoPreview'),youtubePreview=$('youtubePreview'),youtubeThumb=$('youtubeThumb'),youtubeLink=$('youtubeLink');
function setStatus(m,t='ok'){statusBox.textContent=m;statusBox.className='status '+t}
function base(){let u=location.href;return u.substring(0,u.lastIndexOf('/')+1)}
function ytId(url){for(const p of [/youtu\.be\/([A-Za-z0-9_-]{6,})/,/youtube\.com\/watch\?v=([A-Za-z0-9_-]{6,})/,/youtube\.com\/embed\/([A-Za-z0-9_-]{6,})/,/youtube\.com\/shorts\/([A-Za-z0-9_-]{6,})/]){let m=url.match(p);if(m)return m[1]}try{return new URL(url).searchParams.get('v')||''}catch{return''}}
function detect(url){let s=mediaTypeInput.value,c=url.split('?')[0].toLowerCase();if(s!=='auto')return s;if(/youtube\.com|youtu\.be/.test(url))return'youtube';if(/\.(mp4|webm|ogg|mov|m4v)$/.test(c))return'video';return'image'}
function arUrl(){let u=mediaUrlInput.value.trim(),t=titleInput.value.trim(),b=(baseUrlInput.value.trim()||base()).replace(/index\.html$/i,'');if(!u)return'';let type=detect(u);return `${b}marker-ar.html?type=${encodeURIComponent(type)}&data=${encodeURIComponent(u)}&title=${encodeURIComponent(t)}`}
function resetPrev(){previewWrap.classList.add('hidden');imagePreview.classList.add('hidden');videoPreview.classList.add('hidden');youtubePreview.classList.add('hidden');imagePreview.removeAttribute('src');videoPreview.removeAttribute('src');youtubeThumb.removeAttribute('src')}
function testContent(){let u=mediaUrlInput.value.trim();if(!u){setStatus('Pega primero el URL del contenido.','error');return}resetPrev();let type=detect(u);setStatus('Probando contenido...','warn');if(type==='youtube'){let id=ytId(u);if(!id){setStatus('No pude identificar el video de YouTube.','error');return}youtubeThumb.src=`https://img.youtube.com/vi/${id}/hqdefault.jpg`;youtubeLink.href=u;youtubePreview.classList.remove('hidden');previewWrap.classList.remove('hidden');setStatus('YouTube detectado. Se mostrará una miniatura en AR y un botón para abrir el video.','ok');return}if(type==='video'){let tester=document.createElement('video');tester.muted=true;tester.playsInline=true;tester.preload='metadata';tester.onloadedmetadata=()=>{videoPreview.src=u;videoPreview.classList.remove('hidden');previewWrap.classList.remove('hidden');setStatus('El video se cargó correctamente.','ok')};tester.onerror=()=>setStatus('El video no se pudo validar. Aun así puedes generar el QR si el enlace es directo y tiene permisos.','warn');tester.src=u;return}let tester=new Image();tester.onload=()=>{imagePreview.src=u;imagePreview.classList.remove('hidden');previewWrap.classList.remove('hidden');setStatus('La imagen se cargó correctamente. Si es PNG transparente, el fondo quedará transparente en AR.','ok')};tester.onerror=()=>setStatus('La imagen no se pudo validar. Aun así puedes generar el QR si el enlace tiene permisos.','warn');tester.src=u}
function generate(){let a=arUrl();if(!a){setStatus('Falta el URL del contenido.','error');return}resultUrl.value=a;openBtn.href=a;openBtn.classList.remove('disabled');let qr=`https://api.qrserver.com/v1/create-qr-code/?size=360x360&format=png&data=${encodeURIComponent(a)}`;qrBox.innerHTML=`<img crossorigin="anonymous" src="${qr}" alt="QR Code">`;downloadQrBtn.href=qr;downloadQrBtn.classList.remove('disabled');setStatus('QR creado. Descarga el QR Code y el marcador INTER SG.','ok')}
baseUrlInput.value=base();testBtn.addEventListener('click',testContent);generateBtn.addEventListener('click',generate)
