
const $ = id => document.getElementById(id);
const contentTypeInput = $('contentType'), docUrlInput = $('docUrl'), titleInput = $('title'), descriptionInput = $('description'), baseUrlInput = $('baseUrl');
const testBtn = $('testBtn'), generateBtn = $('generateBtn'), statusBox = $('status'), previewWrap = $('previewWrap'), previewFrame = $('previewFrame'), previewOpenBtn = $('previewOpenBtn');
const resultUrl = $('resultUrl'), oneImagePreview = $('oneImagePreview'), downloadSingleBtn = $('downloadSingleBtn'), openBtn = $('openBtn');
function setStatus(message, type='ok'){statusBox.textContent=message;statusBox.className=`status ${type}`;}
function currentBaseUrl(){const c=window.location.href; return c.substring(0, c.lastIndexOf('/')+1);}
function detectType(url){const s=contentTypeInput.value; const clean=url.split('?')[0].toLowerCase(); if(s!=='auto') return s; if(clean.endsWith('.pdf')) return 'pdf'; return 'link';}
function buildArUrl(){const u=docUrlInput.value.trim(), t=titleInput.value.trim(), d=descriptionInput.value.trim(); const b=(baseUrlInput.value.trim()||currentBaseUrl()).replace(/index\.html$/i,''); if(!u) return ''; const type=detectType(u); return `${b}viewer-ar.html?type=${encodeURIComponent(type)}&data=${encodeURIComponent(u)}&title=${encodeURIComponent(t)}&description=${encodeURIComponent(d)}`;}
function testLink(){const u=docUrlInput.value.trim(); if(!u){setStatus('Pega primero el URL del documento o enlace.','error'); return;} previewFrame.src=u; previewOpenBtn.href=u; previewWrap.classList.remove('hidden'); setStatus('Vista previa cargada. Si Blackboard bloquea el PDF, use Abrir en pestaña nueva.','warn');}
function loadImage(src){return new Promise((res,rej)=>{const img=new Image(); img.crossOrigin='anonymous'; img.onload=()=>res(img); img.onerror=rej; img.src=src;});}
function drawRoundRect(ctx,x,y,w,h,r,fill,stroke){ctx.beginPath();ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath(); if(fill){ctx.fillStyle=fill;ctx.fill();} if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=4;ctx.stroke();}}
function wrapText(ctx,text,x,y,maxWidth,lineHeight,maxLines=2){const words=text.split(' '); let line=''; const lines=[]; for(const word of words){const test=line+word+' '; if(ctx.measureText(test).width>maxWidth && line){lines.push(line.trim()); line=word+' ';}else{line=test;}} lines.push(line.trim()); lines.slice(0,maxLines).forEach((ln,i)=>ctx.fillText(ln,x,y+(i*lineHeight)));}
async function buildSingleImage(qrUrl,titleText,descriptionText){const qr=await loadImage(qrUrl); const marker=await loadImage('assets/inter-sg-marker.png'); const canvas=document.createElement('canvas'); canvas.width=1600; canvas.height=1800; const ctx=canvas.getContext('2d'); ctx.fillStyle='#ffffff'; ctx.fillRect(0,0,canvas.width,canvas.height); drawRoundRect(ctx,60,60,1480,1680,44,'#ffffff','#007B5F'); ctx.fillStyle='#007B5F'; ctx.font='bold 58px Arial'; ctx.textAlign='center'; ctx.fillText('AR PDF/Link INTER SG',800,140); ctx.fillStyle='#14211d'; ctx.font='bold 40px Arial'; ctx.fillText(titleText||'Documento AR',800,205); ctx.fillStyle='#5d716b'; ctx.font='28px Arial'; ctx.fillText('Escanea el QR y luego usa el Marker INTER SG del centro',800,255); 
// big qr
ctx.drawImage(qr,200,330,1200,1200); 
// marker centered inside the QR Code. Keep it at 30% of the QR width so the QR remains scannable with ECC H.
ctx.fillStyle='#ffffff'; drawRoundRect(ctx,615,745,370,370,24,'#ffffff','#d7e5e0'); ctx.drawImage(marker,635,765,330,330);
ctx.fillStyle='#14211d'; ctx.font='bold 24px Arial'; ctx.fillText('QR Code + Marker INTER SG en una sola imagen',800,1280);
if(descriptionText){ctx.fillStyle='#14211d'; ctx.font='24px Arial'; wrapText(ctx, descriptionText, 800, 1355, 1040, 30, 3);}
drawRoundRect(ctx,210,1530,1180,120,28,'#FFF4CC','#FED141'); ctx.fillStyle='#14211d'; ctx.font='bold 24px Arial'; wrapText(ctx, 'Publique o imprima esta imagen. El estudiante debe escanear el QR y luego apuntar al mismo Marker INTER SG para abrir el documento o enlace.', 800, 1575, 1040, 30, 3);
return canvas.toDataURL('image/png');}
async function generate(){const arUrl=buildArUrl(); if(!arUrl){setStatus('Falta el URL del documento o enlace.','error'); return;} resultUrl.value=arUrl; openBtn.href=arUrl; openBtn.classList.remove('disabled'); const qrUrl=`https://api.qrserver.com/v1/create-qr-code/?size=1200x1200&format=png&ecc=H&margin=20&data=${encodeURIComponent(arUrl)}`; setStatus('Creando imagen única...','warn'); try{const single=await buildSingleImage(qrUrl, titleInput.value.trim(), descriptionInput.value.trim()); oneImagePreview.innerHTML=`<img src="${single}" alt="QR con Marker INTER SG en el centro">`; downloadSingleBtn.href=single; downloadSingleBtn.classList.remove('disabled'); setStatus('Listo. Descarga la imagen única.','ok');}catch(e){oneImagePreview.innerHTML='<p>No se pudo crear la imagen. Intente nuevamente.</p>'; setStatus('No se pudo crear la imagen única.','error');}}
baseUrlInput.value=currentBaseUrl(); testBtn.addEventListener('click',testLink); generateBtn.addEventListener('click',generate);
